
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  ColorModeToggle: typeof import("../../app/components/ColorModeToggle.vue")['default']
  ConnectionDialog: typeof import("../../app/components/connection/ConnectionDialog.vue")['default']
  LayoutAppSidebar: typeof import("../../app/components/layout/AppSidebar.vue")['default']
  LayoutHeader: typeof import("../../app/components/layout/Header.vue")['default']
  QueryEditor: typeof import("../../app/components/query/QueryEditor.vue")['default']
  QueryExplanation: typeof import("../../app/components/query/QueryExplanation.vue")['default']
  ResultsChartView: typeof import("../../app/components/results/ChartView.vue")['default']
  ResultsDataExplanation: typeof import("../../app/components/results/DataExplanation.vue")['default']
  ResultsTable: typeof import("../../app/components/results/ResultsTable.vue")['default']
  ResultsRtdbWatchPanel: typeof import("../../app/components/results/RtdbWatchPanel.vue")['default']
  SchemaExplorer: typeof import("../../app/components/schema/SchemaExplorer.vue")['default']
  SchemaKnowledgeBase: typeof import("../../app/components/schema/SchemaKnowledgeBase.vue")['default']
  SharedCommandPalette: typeof import("../../app/components/shared/CommandPalette.vue")['default']
  SharedExportDialog: typeof import("../../app/components/shared/ExportDialog.vue")['default']
  SharedUpdateBanner: typeof import("../../app/components/shared/UpdateBanner.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  Accordion: typeof import("../../app/components/ui/accordion/index")['Accordion']
  AccordionContent: typeof import("../../app/components/ui/accordion/index")['AccordionContent']
  AccordionItem: typeof import("../../app/components/ui/accordion/index")['AccordionItem']
  AccordionTrigger: typeof import("../../app/components/ui/accordion/index")['AccordionTrigger']
  AlertDialog: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialog']
  AlertDialogAction: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogAction']
  AlertDialogCancel: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogCancel']
  AlertDialogContent: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogContent']
  AlertDialogDescription: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogDescription']
  AlertDialogFooter: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogFooter']
  AlertDialogHeader: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogHeader']
  AlertDialogTitle: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTitle']
  AlertDialogTrigger: typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTrigger']
  Badge: typeof import("../../app/components/ui/badge/index")['Badge']
  Button: typeof import("../../app/components/ui/button/index")['Button']
  Card: typeof import("../../app/components/ui/card/index")['Card']
  CardAction: typeof import("../../app/components/ui/card/index")['CardAction']
  CardContent: typeof import("../../app/components/ui/card/index")['CardContent']
  CardDescription: typeof import("../../app/components/ui/card/index")['CardDescription']
  CardFooter: typeof import("../../app/components/ui/card/index")['CardFooter']
  CardHeader: typeof import("../../app/components/ui/card/index")['CardHeader']
  CardTitle: typeof import("../../app/components/ui/card/index")['CardTitle']
  Collapsible: typeof import("../../app/components/ui/collapsible/index")['Collapsible']
  CollapsibleContent: typeof import("../../app/components/ui/collapsible/index")['CollapsibleContent']
  CollapsibleTrigger: typeof import("../../app/components/ui/collapsible/index")['CollapsibleTrigger']
  Command: typeof import("../../app/components/ui/command/index")['Command']
  CommandDialog: typeof import("../../app/components/ui/command/index")['CommandDialog']
  CommandEmpty: typeof import("../../app/components/ui/command/index")['CommandEmpty']
  CommandGroup: typeof import("../../app/components/ui/command/index")['CommandGroup']
  CommandInput: typeof import("../../app/components/ui/command/index")['CommandInput']
  CommandItem: typeof import("../../app/components/ui/command/index")['CommandItem']
  CommandList: typeof import("../../app/components/ui/command/index")['CommandList']
  CommandSeparator: typeof import("../../app/components/ui/command/index")['CommandSeparator']
  CommandShortcut: typeof import("../../app/components/ui/command/index")['CommandShortcut']
  Dialog: typeof import("../../app/components/ui/dialog/index")['Dialog']
  DialogClose: typeof import("../../app/components/ui/dialog/index")['DialogClose']
  DialogContent: typeof import("../../app/components/ui/dialog/index")['DialogContent']
  DialogDescription: typeof import("../../app/components/ui/dialog/index")['DialogDescription']
  DialogFooter: typeof import("../../app/components/ui/dialog/index")['DialogFooter']
  DialogHeader: typeof import("../../app/components/ui/dialog/index")['DialogHeader']
  DialogOverlay: typeof import("../../app/components/ui/dialog/index")['DialogOverlay']
  DialogScrollContent: typeof import("../../app/components/ui/dialog/index")['DialogScrollContent']
  DialogTitle: typeof import("../../app/components/ui/dialog/index")['DialogTitle']
  DialogTrigger: typeof import("../../app/components/ui/dialog/index")['DialogTrigger']
  DropdownMenu: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenu']
  DropdownMenuCheckboxItem: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
  DropdownMenuContent: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuContent']
  DropdownMenuGroup: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']
  DropdownMenuItem: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuItem']
  DropdownMenuLabel: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']
  DropdownMenuRadioGroup: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
  DropdownMenuRadioItem: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
  DropdownMenuSeparator: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']
  DropdownMenuShortcut: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']
  DropdownMenuSub: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSub']
  DropdownMenuSubContent: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']
  DropdownMenuSubTrigger: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
  DropdownMenuTrigger: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']
  DropdownMenuPortal: typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']
  Input: typeof import("../../app/components/ui/input/index")['Input']
  Label: typeof import("../../app/components/ui/label/index")['Label']
  ScrollArea: typeof import("../../app/components/ui/scroll-area/index")['ScrollArea']
  ScrollBar: typeof import("../../app/components/ui/scroll-area/index")['ScrollBar']
  Progress: typeof import("../../app/components/ui/progress/index")['Progress']
  Select: typeof import("../../app/components/ui/select/index")['Select']
  SelectContent: typeof import("../../app/components/ui/select/index")['SelectContent']
  SelectGroup: typeof import("../../app/components/ui/select/index")['SelectGroup']
  SelectItem: typeof import("../../app/components/ui/select/index")['SelectItem']
  SelectItemText: typeof import("../../app/components/ui/select/index")['SelectItemText']
  SelectLabel: typeof import("../../app/components/ui/select/index")['SelectLabel']
  SelectScrollDownButton: typeof import("../../app/components/ui/select/index")['SelectScrollDownButton']
  SelectScrollUpButton: typeof import("../../app/components/ui/select/index")['SelectScrollUpButton']
  SelectSeparator: typeof import("../../app/components/ui/select/index")['SelectSeparator']
  SelectTrigger: typeof import("../../app/components/ui/select/index")['SelectTrigger']
  SelectValue: typeof import("../../app/components/ui/select/index")['SelectValue']
  Separator: typeof import("../../app/components/ui/separator/index")['Separator']
  Sheet: typeof import("../../app/components/ui/sheet/index")['Sheet']
  SheetClose: typeof import("../../app/components/ui/sheet/index")['SheetClose']
  SheetContent: typeof import("../../app/components/ui/sheet/index")['SheetContent']
  SheetDescription: typeof import("../../app/components/ui/sheet/index")['SheetDescription']
  SheetFooter: typeof import("../../app/components/ui/sheet/index")['SheetFooter']
  SheetHeader: typeof import("../../app/components/ui/sheet/index")['SheetHeader']
  SheetTitle: typeof import("../../app/components/ui/sheet/index")['SheetTitle']
  SheetTrigger: typeof import("../../app/components/ui/sheet/index")['SheetTrigger']
  Sidebar: typeof import("../../app/components/ui/sidebar/index")['Sidebar']
  SidebarContent: typeof import("../../app/components/ui/sidebar/index")['SidebarContent']
  SidebarFooter: typeof import("../../app/components/ui/sidebar/index")['SidebarFooter']
  SidebarGroup: typeof import("../../app/components/ui/sidebar/index")['SidebarGroup']
  SidebarGroupAction: typeof import("../../app/components/ui/sidebar/index")['SidebarGroupAction']
  SidebarGroupContent: typeof import("../../app/components/ui/sidebar/index")['SidebarGroupContent']
  SidebarGroupLabel: typeof import("../../app/components/ui/sidebar/index")['SidebarGroupLabel']
  SidebarHeader: typeof import("../../app/components/ui/sidebar/index")['SidebarHeader']
  SidebarInput: typeof import("../../app/components/ui/sidebar/index")['SidebarInput']
  SidebarInset: typeof import("../../app/components/ui/sidebar/index")['SidebarInset']
  SidebarMenu: typeof import("../../app/components/ui/sidebar/index")['SidebarMenu']
  SidebarMenuAction: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuAction']
  SidebarMenuBadge: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuBadge']
  SidebarMenuButton: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuButton']
  SidebarMenuItem: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuItem']
  SidebarMenuSkeleton: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSkeleton']
  SidebarMenuSub: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSub']
  SidebarMenuSubButton: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubButton']
  SidebarMenuSubItem: typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubItem']
  SidebarProvider: typeof import("../../app/components/ui/sidebar/index")['SidebarProvider']
  SidebarRail: typeof import("../../app/components/ui/sidebar/index")['SidebarRail']
  SidebarSeparator: typeof import("../../app/components/ui/sidebar/index")['SidebarSeparator']
  SidebarTrigger: typeof import("../../app/components/ui/sidebar/index")['SidebarTrigger']
  Skeleton: typeof import("../../app/components/ui/skeleton/index")['Skeleton']
  Tabs: typeof import("../../app/components/ui/tabs/index")['Tabs']
  TabsContent: typeof import("../../app/components/ui/tabs/index")['TabsContent']
  TabsList: typeof import("../../app/components/ui/tabs/index")['TabsList']
  TabsTrigger: typeof import("../../app/components/ui/tabs/index")['TabsTrigger']
  Tooltip: typeof import("../../app/components/ui/tooltip/index")['Tooltip']
  TooltipContent: typeof import("../../app/components/ui/tooltip/index")['TooltipContent']
  TooltipProvider: typeof import("../../app/components/ui/tooltip/index")['TooltipProvider']
  TooltipTrigger: typeof import("../../app/components/ui/tooltip/index")['TooltipTrigger']
  Textarea: typeof import("../../app/components/ui/textarea/index")['Textarea']
  ColorScheme: typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
  Icon: typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyColorModeToggle: LazyComponent<typeof import("../../app/components/ColorModeToggle.vue")['default']>
  LazyConnectionDialog: LazyComponent<typeof import("../../app/components/connection/ConnectionDialog.vue")['default']>
  LazyLayoutAppSidebar: LazyComponent<typeof import("../../app/components/layout/AppSidebar.vue")['default']>
  LazyLayoutHeader: LazyComponent<typeof import("../../app/components/layout/Header.vue")['default']>
  LazyQueryEditor: LazyComponent<typeof import("../../app/components/query/QueryEditor.vue")['default']>
  LazyQueryExplanation: LazyComponent<typeof import("../../app/components/query/QueryExplanation.vue")['default']>
  LazyResultsChartView: LazyComponent<typeof import("../../app/components/results/ChartView.vue")['default']>
  LazyResultsDataExplanation: LazyComponent<typeof import("../../app/components/results/DataExplanation.vue")['default']>
  LazyResultsTable: LazyComponent<typeof import("../../app/components/results/ResultsTable.vue")['default']>
  LazyResultsRtdbWatchPanel: LazyComponent<typeof import("../../app/components/results/RtdbWatchPanel.vue")['default']>
  LazySchemaExplorer: LazyComponent<typeof import("../../app/components/schema/SchemaExplorer.vue")['default']>
  LazySchemaKnowledgeBase: LazyComponent<typeof import("../../app/components/schema/SchemaKnowledgeBase.vue")['default']>
  LazySharedCommandPalette: LazyComponent<typeof import("../../app/components/shared/CommandPalette.vue")['default']>
  LazySharedExportDialog: LazyComponent<typeof import("../../app/components/shared/ExportDialog.vue")['default']>
  LazySharedUpdateBanner: LazyComponent<typeof import("../../app/components/shared/UpdateBanner.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyAccordion: LazyComponent<typeof import("../../app/components/ui/accordion/index")['Accordion']>
  LazyAccordionContent: LazyComponent<typeof import("../../app/components/ui/accordion/index")['AccordionContent']>
  LazyAccordionItem: LazyComponent<typeof import("../../app/components/ui/accordion/index")['AccordionItem']>
  LazyAccordionTrigger: LazyComponent<typeof import("../../app/components/ui/accordion/index")['AccordionTrigger']>
  LazyAlertDialog: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialog']>
  LazyAlertDialogAction: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogAction']>
  LazyAlertDialogCancel: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogCancel']>
  LazyAlertDialogContent: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogContent']>
  LazyAlertDialogDescription: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogDescription']>
  LazyAlertDialogFooter: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogFooter']>
  LazyAlertDialogHeader: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogHeader']>
  LazyAlertDialogTitle: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTitle']>
  LazyAlertDialogTrigger: LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTrigger']>
  LazyBadge: LazyComponent<typeof import("../../app/components/ui/badge/index")['Badge']>
  LazyButton: LazyComponent<typeof import("../../app/components/ui/button/index")['Button']>
  LazyCard: LazyComponent<typeof import("../../app/components/ui/card/index")['Card']>
  LazyCardAction: LazyComponent<typeof import("../../app/components/ui/card/index")['CardAction']>
  LazyCardContent: LazyComponent<typeof import("../../app/components/ui/card/index")['CardContent']>
  LazyCardDescription: LazyComponent<typeof import("../../app/components/ui/card/index")['CardDescription']>
  LazyCardFooter: LazyComponent<typeof import("../../app/components/ui/card/index")['CardFooter']>
  LazyCardHeader: LazyComponent<typeof import("../../app/components/ui/card/index")['CardHeader']>
  LazyCardTitle: LazyComponent<typeof import("../../app/components/ui/card/index")['CardTitle']>
  LazyCollapsible: LazyComponent<typeof import("../../app/components/ui/collapsible/index")['Collapsible']>
  LazyCollapsibleContent: LazyComponent<typeof import("../../app/components/ui/collapsible/index")['CollapsibleContent']>
  LazyCollapsibleTrigger: LazyComponent<typeof import("../../app/components/ui/collapsible/index")['CollapsibleTrigger']>
  LazyCommand: LazyComponent<typeof import("../../app/components/ui/command/index")['Command']>
  LazyCommandDialog: LazyComponent<typeof import("../../app/components/ui/command/index")['CommandDialog']>
  LazyCommandEmpty: LazyComponent<typeof import("../../app/components/ui/command/index")['CommandEmpty']>
  LazyCommandGroup: LazyComponent<typeof import("../../app/components/ui/command/index")['CommandGroup']>
  LazyCommandInput: LazyComponent<typeof import("../../app/components/ui/command/index")['CommandInput']>
  LazyCommandItem: LazyComponent<typeof import("../../app/components/ui/command/index")['CommandItem']>
  LazyCommandList: LazyComponent<typeof import("../../app/components/ui/command/index")['CommandList']>
  LazyCommandSeparator: LazyComponent<typeof import("../../app/components/ui/command/index")['CommandSeparator']>
  LazyCommandShortcut: LazyComponent<typeof import("../../app/components/ui/command/index")['CommandShortcut']>
  LazyDialog: LazyComponent<typeof import("../../app/components/ui/dialog/index")['Dialog']>
  LazyDialogClose: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogClose']>
  LazyDialogContent: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogContent']>
  LazyDialogDescription: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogDescription']>
  LazyDialogFooter: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogFooter']>
  LazyDialogHeader: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogHeader']>
  LazyDialogOverlay: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogOverlay']>
  LazyDialogScrollContent: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogScrollContent']>
  LazyDialogTitle: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogTitle']>
  LazyDialogTrigger: LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogTrigger']>
  LazyDropdownMenu: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenu']>
  LazyDropdownMenuCheckboxItem: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
  LazyDropdownMenuContent: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuContent']>
  LazyDropdownMenuGroup: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']>
  LazyDropdownMenuItem: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuItem']>
  LazyDropdownMenuLabel: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']>
  LazyDropdownMenuRadioGroup: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
  LazyDropdownMenuRadioItem: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
  LazyDropdownMenuSeparator: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
  LazyDropdownMenuShortcut: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
  LazyDropdownMenuSub: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSub']>
  LazyDropdownMenuSubContent: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
  LazyDropdownMenuSubTrigger: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
  LazyDropdownMenuTrigger: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
  LazyDropdownMenuPortal: LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']>
  LazyInput: LazyComponent<typeof import("../../app/components/ui/input/index")['Input']>
  LazyLabel: LazyComponent<typeof import("../../app/components/ui/label/index")['Label']>
  LazyScrollArea: LazyComponent<typeof import("../../app/components/ui/scroll-area/index")['ScrollArea']>
  LazyScrollBar: LazyComponent<typeof import("../../app/components/ui/scroll-area/index")['ScrollBar']>
  LazyProgress: LazyComponent<typeof import("../../app/components/ui/progress/index")['Progress']>
  LazySelect: LazyComponent<typeof import("../../app/components/ui/select/index")['Select']>
  LazySelectContent: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectContent']>
  LazySelectGroup: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectGroup']>
  LazySelectItem: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectItem']>
  LazySelectItemText: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectItemText']>
  LazySelectLabel: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectLabel']>
  LazySelectScrollDownButton: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectScrollDownButton']>
  LazySelectScrollUpButton: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectScrollUpButton']>
  LazySelectSeparator: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectSeparator']>
  LazySelectTrigger: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectTrigger']>
  LazySelectValue: LazyComponent<typeof import("../../app/components/ui/select/index")['SelectValue']>
  LazySeparator: LazyComponent<typeof import("../../app/components/ui/separator/index")['Separator']>
  LazySheet: LazyComponent<typeof import("../../app/components/ui/sheet/index")['Sheet']>
  LazySheetClose: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetClose']>
  LazySheetContent: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetContent']>
  LazySheetDescription: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetDescription']>
  LazySheetFooter: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetFooter']>
  LazySheetHeader: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetHeader']>
  LazySheetTitle: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetTitle']>
  LazySheetTrigger: LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetTrigger']>
  LazySidebar: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['Sidebar']>
  LazySidebarContent: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarContent']>
  LazySidebarFooter: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarFooter']>
  LazySidebarGroup: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroup']>
  LazySidebarGroupAction: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupAction']>
  LazySidebarGroupContent: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupContent']>
  LazySidebarGroupLabel: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupLabel']>
  LazySidebarHeader: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarHeader']>
  LazySidebarInput: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarInput']>
  LazySidebarInset: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarInset']>
  LazySidebarMenu: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenu']>
  LazySidebarMenuAction: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuAction']>
  LazySidebarMenuBadge: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuBadge']>
  LazySidebarMenuButton: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuButton']>
  LazySidebarMenuItem: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuItem']>
  LazySidebarMenuSkeleton: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSkeleton']>
  LazySidebarMenuSub: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSub']>
  LazySidebarMenuSubButton: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubButton']>
  LazySidebarMenuSubItem: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubItem']>
  LazySidebarProvider: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarProvider']>
  LazySidebarRail: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarRail']>
  LazySidebarSeparator: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarSeparator']>
  LazySidebarTrigger: LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarTrigger']>
  LazySkeleton: LazyComponent<typeof import("../../app/components/ui/skeleton/index")['Skeleton']>
  LazyTabs: LazyComponent<typeof import("../../app/components/ui/tabs/index")['Tabs']>
  LazyTabsContent: LazyComponent<typeof import("../../app/components/ui/tabs/index")['TabsContent']>
  LazyTabsList: LazyComponent<typeof import("../../app/components/ui/tabs/index")['TabsList']>
  LazyTabsTrigger: LazyComponent<typeof import("../../app/components/ui/tabs/index")['TabsTrigger']>
  LazyTooltip: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['Tooltip']>
  LazyTooltipContent: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipContent']>
  LazyTooltipProvider: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipProvider']>
  LazyTooltipTrigger: LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipTrigger']>
  LazyTextarea: LazyComponent<typeof import("../../app/components/ui/textarea/index")['Textarea']>
  LazyColorScheme: LazyComponent<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
  LazyIcon: LazyComponent<typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
