/**
 * Frontend helpers for Redis CRUD.
 *
 * Redis doesn't fit the SQL/document model — each key has a TYPE and the
 * write commands differ per type (SET vs HSET vs RPUSH vs SADD vs ZADD).
 * The dialog uses a single JSON textarea but enforces a type-specific
 * shape: hashes are objects, lists/sets are arrays, zsets are
 * `{member: score}` objects.
 */

export function isRedisEngine(engine: string | undefined | null): boolean {
  return engine === 'redis'
}

export type RedisType = 'string' | 'hash' | 'list' | 'set' | 'zset' | 'stream'

export const REDIS_TYPES: { value: RedisType; label: string }[] = [
  { value: 'string', label: 'string  (SET / GET)' },
  { value: 'hash', label: 'hash    (HSET / HGETALL)' },
  { value: 'list', label: 'list    (RPUSH / LRANGE)' },
  { value: 'set', label: 'set     (SADD / SMEMBERS)' },
  { value: 'zset', label: 'zset    (ZADD / ZRANGE)' },
  { value: 'stream', label: 'stream  (XADD / XRANGE)' },
]

export interface RedisKeyView {
  key: string
  type: string
  value: unknown
  ttl_seconds: number
}

/** Pull the row's Redis key out of a preview row. The driver advertises a
 *  `key` column (no underscore — different from the other NoSQL synthetic
 *  PKs). */
export function getRedisKey(row: Record<string, unknown>): string | null {
  const v = row.key
  return typeof v === 'string' && v !== '' ? v : null
}

/** Pull the key's TYPE out of a preview row. Needed for the Edit dialog so
 *  it can route to the right shape of editor without re-asking the server. */
export function getRedisType(row: Record<string, unknown>): RedisType | null {
  const t = row.type
  if (
    t === 'string'
    || t === 'hash'
    || t === 'list'
    || t === 'set'
    || t === 'zset'
    || t === 'stream'
  ) {
    return t
  }
  return null
}

/** Best-guess seed value for a new key of the given type. The placeholders
 *  also help the user remember the shape each type expects. */
export function defaultValueFor(type: RedisType): string {
  switch (type) {
    case 'string': return '"value"'
    case 'hash': return '{\n  "field": "value"\n}'
    case 'list': return '[\n  "item-1",\n  "item-2"\n]'
    case 'set': return '[\n  "member-1",\n  "member-2"\n]'
    case 'zset': return '{\n  "member-1": 1.0,\n  "member-2": 2.0\n}'
    // Stream: the editor takes ONE entry at a time (XADD), shaped as a
    // hash-like object. The entry ID is auto-generated by Redis.
    case 'stream': return '{\n  "field": "value"\n}'
  }
}

export function prettyJson(value: unknown): string {
  return JSON.stringify(value ?? null, null, 2)
}

export interface JsonValidation {
  ok: boolean
  error?: string
}

/** Validate that `raw` parses as JSON AND fits the shape Redis expects for
 *  the chosen key type. */
export function validateForType(raw: string, type: RedisType): JsonValidation {
  const trimmed = raw.trim()
  if (trimmed === '') return { ok: false, error: 'Value is empty' }
  let parsed: unknown
  try {
    parsed = JSON.parse(trimmed)
  }
  catch (e) {
    return { ok: false, error: (e as Error).message }
  }
  switch (type) {
    case 'string':
      // Strings, numbers, booleans, null all coerce to string server-side.
      // Reject only arrays/objects so the user doesn't get a stringified
      // `[object Object]` written to Redis by accident.
      if (Array.isArray(parsed) || (typeof parsed === 'object' && parsed !== null)) {
        return { ok: false, error: 'String value cannot be a JSON object or array. Use a quoted string or a scalar.' }
      }
      return { ok: true }
    case 'hash':
      if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
        return { ok: false, error: 'Hash value must be a JSON object: { field: value, ... }' }
      }
      return { ok: true }
    case 'list':
    case 'set':
      if (!Array.isArray(parsed)) {
        return { ok: false, error: `${type === 'list' ? 'List' : 'Set'} value must be a JSON array of strings` }
      }
      return { ok: true }
    case 'zset':
      if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
        return { ok: false, error: 'Sorted-set value must be a JSON object: { member: numeric_score, ... }' }
      }
      for (const [member, score] of Object.entries(parsed as Record<string, unknown>)) {
        if (typeof score !== 'number' || !Number.isFinite(score)) {
          return { ok: false, error: `Member '${member}' has a non-numeric score (${typeof score})` }
        }
      }
      return { ok: true }
    case 'stream':
      // Stream insert takes one XADD entry as a flat field/value object.
      if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
        return { ok: false, error: 'Stream entry must be a JSON object: { field: value, ... } (one XADD entry at a time)' }
      }
      if (Object.keys(parsed as Record<string, unknown>).length === 0) {
        return { ok: false, error: 'XADD requires at least one field/value pair' }
      }
      return { ok: true }
  }
}
