
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const ColorModeToggle: typeof import("../app/components/ColorModeToggle.vue")['default']
export const ConnectionDialog: typeof import("../app/components/connection/ConnectionDialog.vue")['default']
export const LayoutAppSidebar: typeof import("../app/components/layout/AppSidebar.vue")['default']
export const LayoutHeader: typeof import("../app/components/layout/Header.vue")['default']
export const QueryEditor: typeof import("../app/components/query/QueryEditor.vue")['default']
export const QueryExplanation: typeof import("../app/components/query/QueryExplanation.vue")['default']
export const ResultsChartView: typeof import("../app/components/results/ChartView.vue")['default']
export const ResultsDataExplanation: typeof import("../app/components/results/DataExplanation.vue")['default']
export const ResultsTable: typeof import("../app/components/results/ResultsTable.vue")['default']
export const SchemaExplorer: typeof import("../app/components/schema/SchemaExplorer.vue")['default']
export const SchemaKnowledgeBase: typeof import("../app/components/schema/SchemaKnowledgeBase.vue")['default']
export const SharedCommandPalette: typeof import("../app/components/shared/CommandPalette.vue")['default']
export const SharedExportDialog: typeof import("../app/components/shared/ExportDialog.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const AlertDialog: typeof import("../app/components/ui/alert-dialog/index")['AlertDialog']
export const AlertDialogAction: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogAction']
export const AlertDialogCancel: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogCancel']
export const AlertDialogContent: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogContent']
export const AlertDialogDescription: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogDescription']
export const AlertDialogFooter: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogFooter']
export const AlertDialogHeader: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogHeader']
export const AlertDialogTitle: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTitle']
export const AlertDialogTrigger: typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTrigger']
export const Accordion: typeof import("../app/components/ui/accordion/index")['Accordion']
export const AccordionContent: typeof import("../app/components/ui/accordion/index")['AccordionContent']
export const AccordionItem: typeof import("../app/components/ui/accordion/index")['AccordionItem']
export const AccordionTrigger: typeof import("../app/components/ui/accordion/index")['AccordionTrigger']
export const Badge: typeof import("../app/components/ui/badge/index")['Badge']
export const Button: typeof import("../app/components/ui/button/index")['Button']
export const Card: typeof import("../app/components/ui/card/index")['Card']
export const CardAction: typeof import("../app/components/ui/card/index")['CardAction']
export const CardContent: typeof import("../app/components/ui/card/index")['CardContent']
export const CardDescription: typeof import("../app/components/ui/card/index")['CardDescription']
export const CardFooter: typeof import("../app/components/ui/card/index")['CardFooter']
export const CardHeader: typeof import("../app/components/ui/card/index")['CardHeader']
export const CardTitle: typeof import("../app/components/ui/card/index")['CardTitle']
export const Command: typeof import("../app/components/ui/command/index")['Command']
export const CommandDialog: typeof import("../app/components/ui/command/index")['CommandDialog']
export const CommandEmpty: typeof import("../app/components/ui/command/index")['CommandEmpty']
export const CommandGroup: typeof import("../app/components/ui/command/index")['CommandGroup']
export const CommandInput: typeof import("../app/components/ui/command/index")['CommandInput']
export const CommandItem: typeof import("../app/components/ui/command/index")['CommandItem']
export const CommandList: typeof import("../app/components/ui/command/index")['CommandList']
export const CommandSeparator: typeof import("../app/components/ui/command/index")['CommandSeparator']
export const CommandShortcut: typeof import("../app/components/ui/command/index")['CommandShortcut']
export const Collapsible: typeof import("../app/components/ui/collapsible/index")['Collapsible']
export const CollapsibleContent: typeof import("../app/components/ui/collapsible/index")['CollapsibleContent']
export const CollapsibleTrigger: typeof import("../app/components/ui/collapsible/index")['CollapsibleTrigger']
export const Input: typeof import("../app/components/ui/input/index")['Input']
export const Dialog: typeof import("../app/components/ui/dialog/index")['Dialog']
export const DialogClose: typeof import("../app/components/ui/dialog/index")['DialogClose']
export const DialogContent: typeof import("../app/components/ui/dialog/index")['DialogContent']
export const DialogDescription: typeof import("../app/components/ui/dialog/index")['DialogDescription']
export const DialogFooter: typeof import("../app/components/ui/dialog/index")['DialogFooter']
export const DialogHeader: typeof import("../app/components/ui/dialog/index")['DialogHeader']
export const DialogOverlay: typeof import("../app/components/ui/dialog/index")['DialogOverlay']
export const DialogScrollContent: typeof import("../app/components/ui/dialog/index")['DialogScrollContent']
export const DialogTitle: typeof import("../app/components/ui/dialog/index")['DialogTitle']
export const DialogTrigger: typeof import("../app/components/ui/dialog/index")['DialogTrigger']
export const DropdownMenu: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenu']
export const DropdownMenuCheckboxItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const DropdownMenuContent: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuContent']
export const DropdownMenuGroup: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const DropdownMenuItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuItem']
export const DropdownMenuLabel: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const DropdownMenuRadioGroup: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const DropdownMenuRadioItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const DropdownMenuSeparator: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const DropdownMenuShortcut: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const DropdownMenuSub: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSub']
export const DropdownMenuSubContent: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const DropdownMenuSubTrigger: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const DropdownMenuTrigger: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const DropdownMenuPortal: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const Label: typeof import("../app/components/ui/label/index")['Label']
export const Select: typeof import("../app/components/ui/select/index")['Select']
export const SelectContent: typeof import("../app/components/ui/select/index")['SelectContent']
export const SelectGroup: typeof import("../app/components/ui/select/index")['SelectGroup']
export const SelectItem: typeof import("../app/components/ui/select/index")['SelectItem']
export const SelectItemText: typeof import("../app/components/ui/select/index")['SelectItemText']
export const SelectLabel: typeof import("../app/components/ui/select/index")['SelectLabel']
export const SelectScrollDownButton: typeof import("../app/components/ui/select/index")['SelectScrollDownButton']
export const SelectScrollUpButton: typeof import("../app/components/ui/select/index")['SelectScrollUpButton']
export const SelectSeparator: typeof import("../app/components/ui/select/index")['SelectSeparator']
export const SelectTrigger: typeof import("../app/components/ui/select/index")['SelectTrigger']
export const SelectValue: typeof import("../app/components/ui/select/index")['SelectValue']
export const ScrollArea: typeof import("../app/components/ui/scroll-area/index")['ScrollArea']
export const ScrollBar: typeof import("../app/components/ui/scroll-area/index")['ScrollBar']
export const Progress: typeof import("../app/components/ui/progress/index")['Progress']
export const Sheet: typeof import("../app/components/ui/sheet/index")['Sheet']
export const SheetClose: typeof import("../app/components/ui/sheet/index")['SheetClose']
export const SheetContent: typeof import("../app/components/ui/sheet/index")['SheetContent']
export const SheetDescription: typeof import("../app/components/ui/sheet/index")['SheetDescription']
export const SheetFooter: typeof import("../app/components/ui/sheet/index")['SheetFooter']
export const SheetHeader: typeof import("../app/components/ui/sheet/index")['SheetHeader']
export const SheetTitle: typeof import("../app/components/ui/sheet/index")['SheetTitle']
export const SheetTrigger: typeof import("../app/components/ui/sheet/index")['SheetTrigger']
export const Sidebar: typeof import("../app/components/ui/sidebar/index")['Sidebar']
export const SidebarContent: typeof import("../app/components/ui/sidebar/index")['SidebarContent']
export const SidebarFooter: typeof import("../app/components/ui/sidebar/index")['SidebarFooter']
export const SidebarGroup: typeof import("../app/components/ui/sidebar/index")['SidebarGroup']
export const SidebarGroupAction: typeof import("../app/components/ui/sidebar/index")['SidebarGroupAction']
export const SidebarGroupContent: typeof import("../app/components/ui/sidebar/index")['SidebarGroupContent']
export const SidebarGroupLabel: typeof import("../app/components/ui/sidebar/index")['SidebarGroupLabel']
export const SidebarHeader: typeof import("../app/components/ui/sidebar/index")['SidebarHeader']
export const SidebarInput: typeof import("../app/components/ui/sidebar/index")['SidebarInput']
export const SidebarInset: typeof import("../app/components/ui/sidebar/index")['SidebarInset']
export const SidebarMenu: typeof import("../app/components/ui/sidebar/index")['SidebarMenu']
export const SidebarMenuAction: typeof import("../app/components/ui/sidebar/index")['SidebarMenuAction']
export const SidebarMenuBadge: typeof import("../app/components/ui/sidebar/index")['SidebarMenuBadge']
export const SidebarMenuButton: typeof import("../app/components/ui/sidebar/index")['SidebarMenuButton']
export const SidebarMenuItem: typeof import("../app/components/ui/sidebar/index")['SidebarMenuItem']
export const SidebarMenuSkeleton: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSkeleton']
export const SidebarMenuSub: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSub']
export const SidebarMenuSubButton: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubButton']
export const SidebarMenuSubItem: typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubItem']
export const SidebarProvider: typeof import("../app/components/ui/sidebar/index")['SidebarProvider']
export const SidebarRail: typeof import("../app/components/ui/sidebar/index")['SidebarRail']
export const SidebarSeparator: typeof import("../app/components/ui/sidebar/index")['SidebarSeparator']
export const SidebarTrigger: typeof import("../app/components/ui/sidebar/index")['SidebarTrigger']
export const Tabs: typeof import("../app/components/ui/tabs/index")['Tabs']
export const TabsContent: typeof import("../app/components/ui/tabs/index")['TabsContent']
export const TabsList: typeof import("../app/components/ui/tabs/index")['TabsList']
export const TabsTrigger: typeof import("../app/components/ui/tabs/index")['TabsTrigger']
export const Separator: typeof import("../app/components/ui/separator/index")['Separator']
export const Tooltip: typeof import("../app/components/ui/tooltip/index")['Tooltip']
export const TooltipContent: typeof import("../app/components/ui/tooltip/index")['TooltipContent']
export const TooltipProvider: typeof import("../app/components/ui/tooltip/index")['TooltipProvider']
export const TooltipTrigger: typeof import("../app/components/ui/tooltip/index")['TooltipTrigger']
export const Skeleton: typeof import("../app/components/ui/skeleton/index")['Skeleton']
export const Textarea: typeof import("../app/components/ui/textarea/index")['Textarea']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyColorModeToggle: LazyComponent<typeof import("../app/components/ColorModeToggle.vue")['default']>
export const LazyConnectionDialog: LazyComponent<typeof import("../app/components/connection/ConnectionDialog.vue")['default']>
export const LazyLayoutAppSidebar: LazyComponent<typeof import("../app/components/layout/AppSidebar.vue")['default']>
export const LazyLayoutHeader: LazyComponent<typeof import("../app/components/layout/Header.vue")['default']>
export const LazyQueryEditor: LazyComponent<typeof import("../app/components/query/QueryEditor.vue")['default']>
export const LazyQueryExplanation: LazyComponent<typeof import("../app/components/query/QueryExplanation.vue")['default']>
export const LazyResultsChartView: LazyComponent<typeof import("../app/components/results/ChartView.vue")['default']>
export const LazyResultsDataExplanation: LazyComponent<typeof import("../app/components/results/DataExplanation.vue")['default']>
export const LazyResultsTable: LazyComponent<typeof import("../app/components/results/ResultsTable.vue")['default']>
export const LazySchemaExplorer: LazyComponent<typeof import("../app/components/schema/SchemaExplorer.vue")['default']>
export const LazySchemaKnowledgeBase: LazyComponent<typeof import("../app/components/schema/SchemaKnowledgeBase.vue")['default']>
export const LazySharedCommandPalette: LazyComponent<typeof import("../app/components/shared/CommandPalette.vue")['default']>
export const LazySharedExportDialog: LazyComponent<typeof import("../app/components/shared/ExportDialog.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyAlertDialog: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialog']>
export const LazyAlertDialogAction: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogAction']>
export const LazyAlertDialogCancel: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogCancel']>
export const LazyAlertDialogContent: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogContent']>
export const LazyAlertDialogDescription: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogDescription']>
export const LazyAlertDialogFooter: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogFooter']>
export const LazyAlertDialogHeader: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogHeader']>
export const LazyAlertDialogTitle: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTitle']>
export const LazyAlertDialogTrigger: LazyComponent<typeof import("../app/components/ui/alert-dialog/index")['AlertDialogTrigger']>
export const LazyAccordion: LazyComponent<typeof import("../app/components/ui/accordion/index")['Accordion']>
export const LazyAccordionContent: LazyComponent<typeof import("../app/components/ui/accordion/index")['AccordionContent']>
export const LazyAccordionItem: LazyComponent<typeof import("../app/components/ui/accordion/index")['AccordionItem']>
export const LazyAccordionTrigger: LazyComponent<typeof import("../app/components/ui/accordion/index")['AccordionTrigger']>
export const LazyBadge: LazyComponent<typeof import("../app/components/ui/badge/index")['Badge']>
export const LazyButton: LazyComponent<typeof import("../app/components/ui/button/index")['Button']>
export const LazyCard: LazyComponent<typeof import("../app/components/ui/card/index")['Card']>
export const LazyCardAction: LazyComponent<typeof import("../app/components/ui/card/index")['CardAction']>
export const LazyCardContent: LazyComponent<typeof import("../app/components/ui/card/index")['CardContent']>
export const LazyCardDescription: LazyComponent<typeof import("../app/components/ui/card/index")['CardDescription']>
export const LazyCardFooter: LazyComponent<typeof import("../app/components/ui/card/index")['CardFooter']>
export const LazyCardHeader: LazyComponent<typeof import("../app/components/ui/card/index")['CardHeader']>
export const LazyCardTitle: LazyComponent<typeof import("../app/components/ui/card/index")['CardTitle']>
export const LazyCommand: LazyComponent<typeof import("../app/components/ui/command/index")['Command']>
export const LazyCommandDialog: LazyComponent<typeof import("../app/components/ui/command/index")['CommandDialog']>
export const LazyCommandEmpty: LazyComponent<typeof import("../app/components/ui/command/index")['CommandEmpty']>
export const LazyCommandGroup: LazyComponent<typeof import("../app/components/ui/command/index")['CommandGroup']>
export const LazyCommandInput: LazyComponent<typeof import("../app/components/ui/command/index")['CommandInput']>
export const LazyCommandItem: LazyComponent<typeof import("../app/components/ui/command/index")['CommandItem']>
export const LazyCommandList: LazyComponent<typeof import("../app/components/ui/command/index")['CommandList']>
export const LazyCommandSeparator: LazyComponent<typeof import("../app/components/ui/command/index")['CommandSeparator']>
export const LazyCommandShortcut: LazyComponent<typeof import("../app/components/ui/command/index")['CommandShortcut']>
export const LazyCollapsible: LazyComponent<typeof import("../app/components/ui/collapsible/index")['Collapsible']>
export const LazyCollapsibleContent: LazyComponent<typeof import("../app/components/ui/collapsible/index")['CollapsibleContent']>
export const LazyCollapsibleTrigger: LazyComponent<typeof import("../app/components/ui/collapsible/index")['CollapsibleTrigger']>
export const LazyInput: LazyComponent<typeof import("../app/components/ui/input/index")['Input']>
export const LazyDialog: LazyComponent<typeof import("../app/components/ui/dialog/index")['Dialog']>
export const LazyDialogClose: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogClose']>
export const LazyDialogContent: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogContent']>
export const LazyDialogDescription: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogDescription']>
export const LazyDialogFooter: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogFooter']>
export const LazyDialogHeader: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogHeader']>
export const LazyDialogOverlay: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogOverlay']>
export const LazyDialogScrollContent: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogScrollContent']>
export const LazyDialogTitle: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogTitle']>
export const LazyDialogTrigger: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogTrigger']>
export const LazyDropdownMenu: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenu']>
export const LazyDropdownMenuCheckboxItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
export const LazyDropdownMenuContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuContent']>
export const LazyDropdownMenuGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']>
export const LazyDropdownMenuItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuItem']>
export const LazyDropdownMenuLabel: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']>
export const LazyDropdownMenuRadioGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
export const LazyDropdownMenuRadioItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
export const LazyDropdownMenuSeparator: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
export const LazyDropdownMenuShortcut: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
export const LazyDropdownMenuSub: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSub']>
export const LazyDropdownMenuSubContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
export const LazyDropdownMenuSubTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
export const LazyDropdownMenuTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
export const LazyDropdownMenuPortal: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']>
export const LazyLabel: LazyComponent<typeof import("../app/components/ui/label/index")['Label']>
export const LazySelect: LazyComponent<typeof import("../app/components/ui/select/index")['Select']>
export const LazySelectContent: LazyComponent<typeof import("../app/components/ui/select/index")['SelectContent']>
export const LazySelectGroup: LazyComponent<typeof import("../app/components/ui/select/index")['SelectGroup']>
export const LazySelectItem: LazyComponent<typeof import("../app/components/ui/select/index")['SelectItem']>
export const LazySelectItemText: LazyComponent<typeof import("../app/components/ui/select/index")['SelectItemText']>
export const LazySelectLabel: LazyComponent<typeof import("../app/components/ui/select/index")['SelectLabel']>
export const LazySelectScrollDownButton: LazyComponent<typeof import("../app/components/ui/select/index")['SelectScrollDownButton']>
export const LazySelectScrollUpButton: LazyComponent<typeof import("../app/components/ui/select/index")['SelectScrollUpButton']>
export const LazySelectSeparator: LazyComponent<typeof import("../app/components/ui/select/index")['SelectSeparator']>
export const LazySelectTrigger: LazyComponent<typeof import("../app/components/ui/select/index")['SelectTrigger']>
export const LazySelectValue: LazyComponent<typeof import("../app/components/ui/select/index")['SelectValue']>
export const LazyScrollArea: LazyComponent<typeof import("../app/components/ui/scroll-area/index")['ScrollArea']>
export const LazyScrollBar: LazyComponent<typeof import("../app/components/ui/scroll-area/index")['ScrollBar']>
export const LazyProgress: LazyComponent<typeof import("../app/components/ui/progress/index")['Progress']>
export const LazySheet: LazyComponent<typeof import("../app/components/ui/sheet/index")['Sheet']>
export const LazySheetClose: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetClose']>
export const LazySheetContent: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetContent']>
export const LazySheetDescription: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetDescription']>
export const LazySheetFooter: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetFooter']>
export const LazySheetHeader: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetHeader']>
export const LazySheetTitle: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetTitle']>
export const LazySheetTrigger: LazyComponent<typeof import("../app/components/ui/sheet/index")['SheetTrigger']>
export const LazySidebar: LazyComponent<typeof import("../app/components/ui/sidebar/index")['Sidebar']>
export const LazySidebarContent: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarContent']>
export const LazySidebarFooter: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarFooter']>
export const LazySidebarGroup: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroup']>
export const LazySidebarGroupAction: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroupAction']>
export const LazySidebarGroupContent: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroupContent']>
export const LazySidebarGroupLabel: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarGroupLabel']>
export const LazySidebarHeader: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarHeader']>
export const LazySidebarInput: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarInput']>
export const LazySidebarInset: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarInset']>
export const LazySidebarMenu: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenu']>
export const LazySidebarMenuAction: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuAction']>
export const LazySidebarMenuBadge: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuBadge']>
export const LazySidebarMenuButton: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuButton']>
export const LazySidebarMenuItem: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuItem']>
export const LazySidebarMenuSkeleton: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSkeleton']>
export const LazySidebarMenuSub: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSub']>
export const LazySidebarMenuSubButton: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubButton']>
export const LazySidebarMenuSubItem: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarMenuSubItem']>
export const LazySidebarProvider: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarProvider']>
export const LazySidebarRail: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarRail']>
export const LazySidebarSeparator: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarSeparator']>
export const LazySidebarTrigger: LazyComponent<typeof import("../app/components/ui/sidebar/index")['SidebarTrigger']>
export const LazyTabs: LazyComponent<typeof import("../app/components/ui/tabs/index")['Tabs']>
export const LazyTabsContent: LazyComponent<typeof import("../app/components/ui/tabs/index")['TabsContent']>
export const LazyTabsList: LazyComponent<typeof import("../app/components/ui/tabs/index")['TabsList']>
export const LazyTabsTrigger: LazyComponent<typeof import("../app/components/ui/tabs/index")['TabsTrigger']>
export const LazySeparator: LazyComponent<typeof import("../app/components/ui/separator/index")['Separator']>
export const LazyTooltip: LazyComponent<typeof import("../app/components/ui/tooltip/index")['Tooltip']>
export const LazyTooltipContent: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipContent']>
export const LazyTooltipProvider: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipProvider']>
export const LazyTooltipTrigger: LazyComponent<typeof import("../app/components/ui/tooltip/index")['TooltipTrigger']>
export const LazySkeleton: LazyComponent<typeof import("../app/components/ui/skeleton/index")['Skeleton']>
export const LazyTextarea: LazyComponent<typeof import("../app/components/ui/textarea/index")['Textarea']>
export const LazyColorScheme: LazyComponent<typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
export const LazyIcon: LazyComponent<typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
